version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: filippopetito/smartshop:latest
    container_name: smartShop
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootmysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql